
SOURCES+=library/aximm/piradip_axi4.sv
SOURCES+=library/aximm/piradip_axi4mmlite.sv
SOURCES+=library/aximm/piradip_register_if.sv

SOURCES+=library/cdc/piradip_cdc.sv

SOURCES+=library/axis/piradip_axis.sv
SOURCES+=library/axis/dsp/piradip_16x4sym.sv

SOURCES+=tb/util/piradip_tb_clocks.sv
SOURCES+=tb/aximm/piradip_tb_aximm_util.sv
SOURCES+=tb/aximm/piradip_tb_aximm_manager.sv

SOURCES+=tb/axis/piradip_axis_util.sv

SOURCES+=tb/axis/piradip_rfdc_util.sv

SOURCES+=tb/axis/dsp/piradip_16x4sym.sv

TOP_MODULE=piradip_tb_16x4sym

include ../include.mk

