#*****************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# test.tcl: Tcl script for re-creating project 'edit_PiRadSPI_v1_0'
#
# Generated by Vivado on Tue Nov 16 12:55:47 -0700 2021
# IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (test.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.svh"
#    "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_engine.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_aximm.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis_fifo.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/component.xml"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.svh"
#    "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_aximm.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/axis/piradip_axis_util.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/util/piradip_tb_clocks.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/aximm/piradip_tb_aximm_util.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axi/piradip_axi4.svh"
#    "C:/Users/zapma/Documents/PiRadIP/piradspi_tb_csr_behav.wcfg"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi.svh"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_engine.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_engine.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_full.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradio_v2_tb_spi_decoder.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_engine_on_board.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv"
#    "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradip_test_logic_chips.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axi/piradip_axi4.svh"
#    "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis_fifo.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/util/piradip_shift_registers.sv"
#    "C:/Users/zapma/Documents/PiRadIP/library/util/piradip_state_timer.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/util/piradip_tb_clocks.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/spi/piradip_tb_spi_slave.sv"
#    "C:/Users/zapma/Documents/PiRadIP/tb/aximm/piradip_tb_aximm_util.sv"
#    "C:/Users/zapma/Documents/PiRadIP/piradspi_tb_full_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.svh" \
   "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_engine.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_aximm.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis_fifo.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/component.xml" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.svh" \
   "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_aximm.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/axis/piradip_axis_util.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/util/piradip_tb_clocks.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/aximm/piradip_tb_aximm_util.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axi/piradip_axi4.svh" \
   "C:/Users/zapma/Documents/PiRadIP/piradspi_tb_csr_behav.wcfg" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi.svh" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_engine.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_engine.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_full.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradio_v2_tb_spi_decoder.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_tb_engine_on_board.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradspi_csr.sv" \
   "C:/Users/zapma/Documents/PiRadIP/PiRadSPI_1.0/hdl/piradip_test_logic_chips.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axi/piradip_axi4.svh" \
   "C:/Users/zapma/Documents/PiRadIP/library/aximm/piradip_axi4mmlite.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis_fifo.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/axis/piradip_axis.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/util/piradip_shift_registers.sv" \
   "C:/Users/zapma/Documents/PiRadIP/library/util/piradip_state_timer.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/util/piradip_tb_clocks.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/spi/piradip_tb_spi_slave.sv" \
   "C:/Users/zapma/Documents/PiRadIP/tb/aximm/piradip_tb_aximm_util.sv" \
   "C:/Users/zapma/Documents/PiRadIP/piradspi_tb_full_behav.wcfg" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set paths [list \
   [file normalize "$origin_dir/PiRaDMA_MM2S_1.0"] \
   [file normalize "$origin_dir/AXILiteTemplate_1.0"] \
   [file normalize "$origin_dir/PiRadSPI_1.0"] \
   [file normalize "$origin_dir/"] \
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "edit_PiRadSPI_v1_0"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "test.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xczu28dr-ffvg1517-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:zcu111:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zcu111" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "1247" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/PiRaDMA_MM2S_1.0"] [file normalize "$origin_dir/AXILiteTemplate_1.0"] [file normalize "$origin_dir/PiRadSPI_1.0"] [file normalize "$origin_dir/"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis.svh" ]\
 [file normalize "${origin_dir}/library/aximm/piradip_axi4mmlite.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_engine.sv" ]\
 [file normalize "${origin_dir}/library/aximm/piradip_aximm.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis_fifo.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_csr.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/component.xml" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "hdl/PiRadSPI_v1_0.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "aximm/piradip_axi4mmlite.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradspi_engine.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "aximm/piradip_aximm.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradspi_csr.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "PiRadSPI_1.0/component.xml"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Unknown" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "PiRadSPI_v1_0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'CSR_TB' fileset (if not found)
if {[string equal [get_filesets -quiet CSR_TB] ""]} {
  create_fileset -simset CSR_TB
}

# Set 'CSR_TB' fileset object
set obj [get_filesets CSR_TB]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_csr.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis.svh" ]\
 [file normalize "${origin_dir}/library/aximm/piradip_axi4mmlite.sv" ]\
 [file normalize "${origin_dir}/library/aximm/piradip_aximm.sv" ]\
 [file normalize "${origin_dir}/tb/axis/piradip_axis_util.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis.sv" ]\
 [file normalize "${origin_dir}/tb/util/piradip_tb_clocks.sv" ]\
 [file normalize "${origin_dir}/tb/aximm/piradip_tb_aximm_util.sv" ]\
 [file normalize "${origin_dir}/library/axi/piradip_axi4.svh" ]\
 [file normalize "${origin_dir}/piradspi_tb_csr_behav.wcfg" ]\
]
set imported_files [import_files -fileset CSR_TB $files]

# Set 'CSR_TB' fileset file properties for remote files
# None

# Set 'CSR_TB' fileset file properties for local files
set file "hdl/piradspi_tb_csr.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradspi_csr.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis.svh"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "aximm/piradip_axi4mmlite.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "aximm/piradip_aximm.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis_util.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "util/piradip_tb_clocks.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "aximm/piradip_tb_aximm_util.sv"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axi/piradip_axi4.svh"
set file_obj [get_files -of_objects [get_filesets CSR_TB] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'CSR_TB' fileset properties
set obj [get_filesets CSR_TB]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "source_set" -value "" -objects $obj
set_property -name "top" -value "piradspi_tb_csr" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "xsim.simulate.runtime" -value "50000ns" -objects $obj

# Create 'FullDevice_TB' fileset (if not found)
if {[string equal [get_filesets -quiet FullDevice_TB] ""]} {
  create_fileset -simset FullDevice_TB
}

# Set 'FullDevice_TB' fileset object
set obj [get_filesets FullDevice_TB]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi.svh" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_engine.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_tb_csr.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/PiRadSPI_v1_0.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_tb_engine.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_tb_full.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradio_v2_tb_spi_decoder.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_tb_engine_on_board.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradspi_csr.sv" ]\
 [file normalize "${origin_dir}/PiRadSPI_1.0/hdl/piradip_test_logic_chips.sv" ]\
 [file normalize "${origin_dir}/library/axi/piradip_axi4.svh" ]\
 [file normalize "${origin_dir}/library/aximm/piradip_axi4mmlite.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis_fifo.sv" ]\
 [file normalize "${origin_dir}/library/axis/piradip_axis.sv" ]\
 [file normalize "${origin_dir}/library/util/piradip_shift_registers.sv" ]\
 [file normalize "${origin_dir}/library/util/piradip_state_timer.sv" ]\
 [file normalize "${origin_dir}/tb/util/piradip_tb_clocks.sv" ]\
 [file normalize "${origin_dir}/tb/spi/piradip_tb_spi_slave.sv" ]\
 [file normalize "${origin_dir}/tb/aximm/piradip_tb_aximm_util.sv" ]\
 [file normalize "${origin_dir}/piradspi_tb_full_behav.wcfg" ]\
]
set imported_files [import_files -fileset FullDevice_TB $files]

# Set 'FullDevice_TB' fileset file properties for remote files
# None

# Set 'FullDevice_TB' fileset file properties for local files
set file "hdl/piradspi.svh"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "hdl/piradspi_engine.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradspi_tb_csr.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "hdl/PiRadSPI_v1_0.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradspi_tb_engine.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "hdl/piradspi_tb_full.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradio_v2_tb_spi_decoder.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "hdl/piradspi_tb_engine_on_board.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "hdl/piradspi_csr.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "hdl/piradip_test_logic_chips.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axi/piradip_axi4.svh"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "aximm/piradip_axi4mmlite.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis_fifo.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "axis/piradip_axis.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "util/piradip_shift_registers.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "util/piradip_state_timer.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "util/piradip_tb_clocks.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "spi/piradip_tb_spi_slave.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "aximm/piradip_tb_aximm_util.sv"
set file_obj [get_files -of_objects [get_filesets FullDevice_TB] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'FullDevice_TB' fileset properties
set obj [get_filesets FullDevice_TB]
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "source_set" -value "" -objects $obj
set_property -name "top" -value "piradspi_tb_full" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "50000ns" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xczu28dr-ffvg1517-2-e -flow {Vivado Synthesis 2020} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xczu28dr-ffvg1517-2-e -flow {Vivado Implementation 2020} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
