
SOURCES=

SOURCES+=library/aximm/piradip_axi4.sv
SOURCES+=library/aximm/piradip_axi4mmlite.sv
SOURCES+=library/aximm/piradip_aximm.sv
SOURCES+=library/aximm/piradip_register_if.sv

SOURCES+=library/fifo/piradip_sync_fifo.sv


SOURCES+=library/mem/piradip_axi4_ram_adapter.sv
SOURCES+=library/mem/piradip_dual_port_ram.sv

SOURCES+=library/cdc/piradip_cdc.sv

SOURCES+=library/util/piradip_latency_synchronizer.sv

SOURCES+=library/axis/piradip_axis.sv
SOURCES+=library/axis/piradip_axis_fifo.sv
SOURCES+=library/axis/piradip_axis_gain_block.sv

SOURCES+=tb/util/piradip_tb_clocks.sv
SOURCES+=tb/axis/piradip_axis_util.sv
SOURCES+=tb/aximm/piradip_tb_aximm_util.sv
SOURCES+=tb/aximm/piradip_tb_aximm_manager.sv

SOURCES+=tb/axis/piradip_tb_axis_gain_block.sv

TOP_MODULE=piradip_tb_axis_gain_block

include ../include.mk

