
SOURCES=

SOURCES+=library/aximm/piradip_axi4.sv
SOURCES+=library/aximm/piradip_axi4mmlite.sv
SOURCES+=library/aximm/piradip_register_if.sv

SOURCES+=library/util/piradip_trigger_unit.sv

SOURCES+=tb/util/piradip_tb_clocks.sv
SOURCES+=tb/aximm/piradip_tb_aximm_util.sv
SOURCES+=tb/aximm/piradip_tb_aximm_manager.sv

SOURCES+=tb/util/piradip_tb_trigger_unit.sv

TOP_MODULE=piradip_tb_trigger_unit

include ../Makefile.inc

